/**
 * 
 */
package container;

/**
 * @author AI10MABR
 *
 */
public class BinauralBeat {
	//Attributes
	private int freq1_start, freq2_start;
	private int freq1_target, freq2_target;
	//Getters and Setters
	public int getFreq1_start() {
		return freq1_start;
	}
	public void setFreq1_start(int freq1_start) {
		this.freq1_start = freq1_start;
	}
	public int getFreq2_start() {
		return freq2_start;
	}
	public void setFreq2_start(int freq2_start) {
		this.freq2_start = freq2_start;
	}
	public int getFreq1_target() {
		return freq1_target;
	}
	public void setFreq1_target(int freq1_target) {
		this.freq1_target = freq1_target;
	}
	public int getFreq2_target() {
		return freq2_target;
	}
	public void setFreq2_target(int freq2_target) {
		this.freq2_target = freq2_target;
	}
	
	//Custom methods
	
	/**
	 * @return the mood that is generated by the the difference of the two frequencies
	 */
	public String getMood(){
		//TODO: implement this!
		// switch-case to select moods from frequencies?
		return "Happy";
	}

}
